# docker-compose.yaml

version: '2' # version of docker-compose to use

services:
  wordpress:
    container_name: cont_wordp_php72 # name of our wordpress container
    ports:
      - "8080:80" # setting our ports for networking
      - "9001:9000" # for xdebug
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes: # this is where we tell Docker what to pay attention to
      - ./www:/var/www/html/ # mapping our custom theme to the container